# Adapted from a public workflow byBen Siranosian (bsiranosian@gmail.com) - Bhatt lab - Stanford Genetics
# https://github.com/bhattlab/bhattlab_workflows/tree/master

# specify directories
raw_reads_directory: raw_data
output_directory: preprocessing
read_specification: ['R1', 'R2'] 
extension: .fastq.gz 

# specify parameters for TrimGalore -- automatically chcecks the adaptor type
trim_galore:
  quality:  30
  min_read_length: 60
  start_trim: 0
  end_trim: 0

rm_host_reads:
  host_genome: <path_to_git_directory>/reference-genomes/bosTau9/bosTau9.fa

