# Adapted from a public workflow by Ben Siranosian (bsiranosian@gmail.com) - Bhatt lab - Stanford Genetics
# https://github.com/bhattlab/kraken2_classification

# Specify sample names and read files
## tab-delimited table with three columns, see manual/usage.md
##    sample_name  read1_file  [read2_file]
##    if paired end, all samples must be paired end
##    if single end, all samples must be single end
## If this file is specified, sample_reports_file must not be specified.
sample_reads_file: '/home/groups/jadebc/cradle-pilot-seq/4-classification-pipeline/snakemake_config_files/classification_input.txt'
# Specify file containing sample groups.
## Tab delimited with two columns, see manual/downstream_plotting.md
## If empty string specified, all samples will be treated as one group.
sample_groups_file: '/home/groups/jadebc/cradle-pilot-seq/4-classification-pipeline/snakemake_config_files/sample_groups.tsv'

# Output base directory - will contain subfolders for reports, plots, etc
outdir: '/home/groups/jadebc/cradle-pilot-seq/'

# Do Bracken calculations and use the results in downstream processing?
run_bracken: True

# Read length of the input data
## Used in the Bracken species reestimation. You must have a Bracken database built with this length
read_length: 150

# Confidence threshold: a recently introduced feature for Kraken
## Increase this to reduce false positives for Kraken
## Maximum 1.0
confidence_threshold: 0.0

# Taxonomic level for Bracken results.
## Currently, only "S" is supported.
taxonomic_level: S

# Database
## Must contain a Kraken2 and Bracken database
database: '/home/groups/jadebc/public/kraken-databases/k2_pluspf_20240112/'

######### Downstream processing options ###################
# Downstream processing for filtering OTUs
## This removes any classification result where all samples are below this threshold,
## which serves to remove the very long tail of lowly abundant species in Kraken2/Bracken results.
## This parameter can be tuned, but I recommend you keep something here to reduce the long tail.
## This parameter is defined as a percentage, so 0.001 = 0.001%
min_otu_percentage: 0.001
# Filters for compositional data analysis, which get applied at each taxonomic level
## Keep only those samples with > 5000 reads
codata_min_reads: 5000
## Keep only OTUs with an PROPORTION of at least 0.001
## This is equivalent to a PERCENTAGE of 0.1
codata_min_prop: 0.001
## Keep OTUs that are found in at least 30% of samples
codata_otu_cutoff: 0.3
# Remove everything in the phylum Chordata?
## This helps to remove pesky human reads from the matrices and plots
remove_chordata: True
###########################################################

########### Extracting unmapped reads #####################
# Extract unmapped reads from this database for use with
## another database. Will be in output folder outdir/unmapped_reads
extract_unmapped: False
###########################################################
